CLASS zcit_cx_22ec301_no_prod DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_t100_message .
    INTERFACES if_t100_dyn_msg .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcit_cx_22ec301_no_prod IMPLEMENTATION.
ENDCLASS.
